version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  app:
    build: .
    depends_on:
      - redis
      - sqlserver
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TradingPlatform;User=sa;Password=YourStrong@Passw0rd;
      - Redis__ConnectionString=redis
      - MarketData__WebSocketUrl=wss://marketdata.example.com/ws
      - FIX__ConfigFile=/app/FixConfig.cfg

volumes:
  redis_data:
  sql_data: